---
Ruhrgebiet:
  gender: das
  cases:
    genetiv: des Ruhrgebiets
  districts:
    - Kreis Mettmann
    - Stadt Mülheim an der Ruhr
    - Stadt Duisburg
    - Stadt Oberhausen
    - Stadt Bottrop
    - Stadt Essen
    - Stadt Gelsenkirchen
    - Stadt Herne
    - Stadt Bochum
    - Stadt Dortmund
    - Stadt Hagen
    - Stadt Hamm
    - Ennepe-Ruhr-Kreis
    - Stadt Wuppertal
    - Kreis Recklinghausen
    - Kreis Unna
    - Kreis Wesel

Köln-Bonner Raum:
  gender: der
  cases:
    genetiv: des Köln-Bonner Raums
  districts:
    - Stadt Köln
    - Rhein-Erft-Kreis
    - Rhein-Sieg-Kreis
    - Bundesstadt Bonn
    - Rheinisch-Bergischer Kreis

Süden von NRW:
  gender: der
  cases:
    genetiv: des Südens von NRW
  districts:
    - Stadt Köln
    - Rhein-Erft-Kreis
    - Rhein-Sieg-Kreis
    - Bundesstadt Bonn
    - Rheinisch-Bergischer Kreis
    - StädteRegion Aachen
    - Kreis Düren
    - Kreis Euskirchen
    - Oberbergischer Kreis
    - Kreis Olpe
    - Kreis Siegen-Wittgenstein

Niederrhein:
  gender: der
  cases:
    genetiv: des Niederrheins
  districts:
    - Kreis Kleve
    - Kreis Wesel
    - Kreis Viersen
    - Kreis Borken
    - Stadt Krefeld
    - Stadt Duisburg
    - Rhein-Kreis Neuss
    - Stadt Mönchengladbach
    - Kreis Heinsberg

Münsterland:
  gender: das
  cases:
    genetiv: des Münsterlandes
  districts:
    - Stadt Münster
    - Kreis Steinfurt
    - Kreis Warendorf
    - Kreis Coesfeld
    - Kreis Borken
    - Stadt Hamm

Nordosten von NRW:
  gender: der
  cases:
    genetiv: des Nordostens von NRW
  districts:
    - Kreis Minden-Lübbecke
    - Kreis Herford
    - Stadt Bielefeld
    - Kreis Gütersloh
    - Kreis Lippe
    - Kreis Paderborn
    - Kreis Höxter
    - Kreis Warendorf

Sauerland:
  gender: das
  cases:
    genetiv: des Sauerlandes
  districts:
    - Kreis Soest
    - Hochsauerlandkreis
    - Märkischer Kreis
    - Kreis Olpe

Siegerland:
  gender: das
  cases:
    genetiv: des Siegerlandes
  districts:
    - Kreis Siegen-Wittgenstein

Westfalen:
  gender: False
  cases:
    genetiv: Westfalens
  districts:
    - Ennepe-Ruhr-Kreis
    - Hochsauerlandkreis
    - Märkischer Kreis
    - Kreis Olpe
    - Kreis Siegen-Wittgenstein
    - Kreis Soest
    - Kreis Unna
    - Stadt Bochum
    - Stadt Dortmund
    - Stadt Hagen
    - Stadt Hamm
    - Stadt Herne
    - Kreis Gütersloh
    - Kreis Herford
    - Kreis Höxter
    - Kreis Minden-Lübbecke
    - Kreis Paderborn
    - Stadt Bielefeld
    - Kreis Lippe
    - Kreis Borken
    - Kreis Coesfeld
    - Kreis Recklinghausen
    - Kreis Steinfurt
    - Kreis Warendorf
    - Stadt Bottrop
    - Stadt Gelsenkirchen
    - Stadt Münster

Rheinland:
  gender: das
  cases:
    genetiv: des Rheinlandes
  districts:
    - StädteRegion Aachen
    - Stadt Bonn
    - Stadt Düsseldorf
    - Stadt Duisburg
    - Stadt Essen
    - Stadt Köln
    - Stadt Krefeld
    - Stadt Leverkusen
    - Stadt Mönchengladbach
    - Stadt Mülheim an der Ruhr
    - Stadt Oberhausen
    - Stadt Remscheid
    - Stadt Solingen
    - Stadt Wuppertal
    - Kreis Kleve
    - Kreis Wesel
    - Kreis Viersen
    - Kreis Heinsberg
    - Rhein-Kreis Neuss
    - Kreis Mettmann
    - Rhein-Erft-Kreis
    - Oberbergischer Kreis
    - Rheinisch-Bergischer Kreis
    - Rhein-Sieg-Kreis
    - Kreis Euskirchen
    - Kreis Düren

Ostwestfalen-Lippe:
  gender: False
  cases:
    genetiv: von Ostwestfalen-Lippe
  districts:
    - Kreis Minden-Lübbecke
    - Kreis Herford
    - Stadt Bielefeld
    - Kreis Gütersloh
    - Kreis Lippe
    - Kreis Paderborn
    - Kreis Höxter

Bergisches Land:
  gender: das
  cases:
    genetiv: des Bergischen Landes
  districts:
    - Stadt Wuppertal
    - Stadt Remscheid
    - Stadt Solingen
    - Kreis Mettmann
    - Stadt Leverkusen
    - Oberbergischer Kreis
    - Rheinisch-Bergischer Kreis
    - Rhein-Sieg-Kreis

Eifel:
  gender: die
  cases:
    genetiv: der Eifel

Soester Boerde:
  gender: die
  cases:
    genetiv: der Soester Boerde
